sonar.projectKey=aziizdobetter_moodle-code-analysis
sonar.organization=aziizdobetter
sonar.host.url=https://sonarcloud.io
sonar.sources=public/course
sonar.exclusions=**/node_modules/**, **/vendor/**, **/test/**, **/tests/**, **/fixtures/**, **/public/lang/**, **/public/theme/**, **/public/userpix/**
