sonar.projectKey=aziizdobetter_moodle-code-analysis
sonar.organization=aziizdobetter
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/vendor/**, **/moodledata/**, **/test/**, **/lib/editor/**, **/lib/thirdparty/**
